### ISSUE TITLE
No layout generated

### ISSUE THREAD

**Issue by adrienfenech** [klugjo/hexo-theme-magnetic#1]
Hello there, 

When I try to generate my blog using Magnetic theme, I get an error on each files under the layout directory:

``` javascript
ERROR Process failed: layout/index.ejs
TypeError: Cannot read property 'compile' of undefined
```

The result is every page generated doesn't get layout.
Do you have an idea ?

Thanks a lot !

**Comment by klugjo** [comment]
I don't think this is related to the theme

https://github.com/hexojs/hexo/issues/1805
https://github.com/hexojs/hexo/issues/1793
https://github.com/hexojs/hexo/issues/1855

Some people said the issue is with hexo 3.2.0

**Comment by leesei** [comment]
This is indeed a Hexo 3.2 issue, tracked by #1855.
