### ISSUE TITLE
New post not displaying header images.

### ISSUE THREAD

**Issue by lexbity** [klugjo/hexo-theme-magnetic#12]
When I create a new post (hexo new <name>) 
 - the content_header  image is not being displayed in the index page.
- the content_detail image is not being displayed

I have the webpage root at "/blog/"

**Comment by lexbity** [comment]
when I have:
`content_header: /blog/assets/img.jpg` it works

am I missing a config in the theme?

**Comment by klugjo** [comment]
Can you give me more details ? I am not sure I am getting it:

- root config.yaml
- theme config.yaml
- post front matter

**Comment by lexbity** [comment]
Here's the [site source](https://github.com/liuprestin/test_blog)
