### ISSUE TITLE
Using relative path on thumbnail

### ISSUE THREAD

**Issue by ghost** [klugjo/hexo-theme-magnetic#18]
Hello Klugjo very nice theme, I have a question, how to use relative path with thumbnail ?

I have turned on the asset option for every post so that for a post like hello I have a hello folder, I put the img in this folder and put the following line in my post

cover_index: /hello/work1.jpg

However it didn't work as I expected......

What should I do exactly ?

Tks !

**Comment by klugjo** [comment]
Can you check the URL in the generated HTML and check what is the actual URL on the server ?

**Comment by klugjo** [comment]
I am closing this for now. Please create a PR if you want to add that functionality
