### ISSUE TITLE
Possibility to link external link to image ?

### ISSUE THREAD

**Issue by ghost** [klugjo/hexo-theme-magnetic#19]
Hello Klugjo another question, is it possible that when the user click the image of index page he will be directed to another link ?

The behavior desired :

1 The user click the image

2 He goes to a site like my gitbook   https://rosingle.gitbooks.io/these_resume_court/content/

would really be cool with this function !

**Comment by klugjo** [comment]
There are no plans on adding this functionality sorry.

**Comment by klugjo** [comment]
Closing this for now, please create a PR if you want to add that functionality
