### ISSUE TITLE
Generate issue

### ISSUE THREAD

**Issue by RomanBogachev** [klugjo/hexo-theme-magnetic#2]
When I try to generate get error. 
Some posts ok.

```
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Аварийный останов
```

**Comment by klugjo** [comment]
This issue is not theme related and looks like a Node/Hexo bug I believe.

Can you give me more info ?

Do you have the latest version of node and hexo ?

http://stackoverflow.com/questions/24419442/noe-js-error-terminate-called-after-throwing-an-instance-of-stdbad-alloc-wh

**Comment by RomanBogachev** [comment]
Yes, I installed the latest version of Hexo.

```
[root@R-Bogachev ~]# hexo --version
hexo-cli: 1.0.1
os: Linux 3.10.0-327.10.1.el7.x86_64 linux x64
http_parser: 1.1
node: 0.10.42
v8: 3.14.5.9
ares: 1.9.0-DEV
uv: 0.10.34
zlib: 1.2.7
modules: 11
openssl: 1.0.1e-fips
```

I have files ~190Mb. I use them in asset folders.
How can I increase value for this?

**Comment by klugjo** [comment]
I am afraid I am not able to help. That could be a limitation of Node or Hexo. 190 MB sounds huge !

Have you tried with the default Hexo Theme ? Do you have the same issue ?

I think you should ask your question on the Hexo github project.

https://github.com/hexojs/hexo

**Comment by RomanBogachev** [comment]
Yes, at default theme was the same problem.

**Comment by klugjo** [comment]
Ok. 

You will get better help on the Hexo project. https://github.com/hexojs/hexo

Thanks for giving Magnetic a try !
