### ISSUE TITLE
Cover index pictures not shown in second page

### ISSUE THREAD

**Issue by tvntran** [klugjo/hexo-theme-magnetic#24]
Cover index pictures are shown perfectly in the homepage, but disappear from the second page.
Here I set 2 posts per page, and this is [page 2](https://www.dropbox.com/s/f7bnwt66hf1u7k8/Skjermbilde%202018-06-25%20kl.%2010.47.40.png?dl=0).
Do you have any idea to fix the problem? Thanks!

**Comment by klugjo** [comment]
Do you a have a link to your live blog ? Can you also paste the front matter for the posts ? I need to see how you set up the path to the cover images.

Thanks for using my theme :)

**Comment by tvntran** [comment]
I don't think there is any problem with the front matter, because everything looks perfect when I set `per_page: 0`, and if I forget, it should show the default cover index.
Here is my site [tiengnauy.no](http://tiengnauy.no). I will change it to another value and let you know.
The theme is great with its minimalism. Thank you for your work!

**Comment by klugjo** [comment]
I am just thinking there is an issue with relative/absolute path to the
images. So when you are on the root page it works, but when you are on
page/2 it fails because it can’t find the images

**Comment by tvntran** [comment]
Oh, I see. I use relative link. It could be the cause.

**Comment by klugjo** [comment]
Try to use absolute path for now then I will have a look and fix it for
relative path if that is the cause

**Comment by tvntran** [comment]
I confirm that it works when I use absolute links for the images. Thank for your support!
