### ISSUE TITLE
cover_detail doesn't show in my post

### ISSUE THREAD

**Issue by damarindra** [klugjo/hexo-theme-magnetic#25]
Regarding the documentation, it says I only need to add `cover_detail : assets/coverdetail.jpg` right? Images don't show in my post.

This is my Front-matter 
```
title: codecanyon
date: 2019-02-14 11:26:50
cover_detail: assets/coverdetail.jpg
cover_index: assets/cover.jpg
```

have tried this one
```
title: codecanyon
date: 2019-02-14 11:26:50
cover_detail: /assets/coverdetail.jpg
cover_index: /assets/cover.jpg
```
still doesn't work

-UPDATE-
Galery also doesn't work, I'm using gh-pages branch for this. It might be the reason(?)
```
title: Codecanyon
date: 2019-02-14 11:26:50
cover_detail: /assets/coverdetail.jpg
cover_index: assets/cover.jpg
photos:
- assets/codecanyon/crossyway.JPG
- assets/codecanyon/distortion.JPG
- assets/codecanyon/down.JPG
- assets/codecanyon/dropdots.JPG
- assets/codecanyon/jumping.JPG
- assets/codecanyon/rects.JPG
```

you can see it here : https://damarindra.github.io/portfolio/

**Comment by klugjo** [comment]
I do not see any issue with you site

**Comment by klugjo** [comment]
I think you need to put /porfolio/ in front because your site is not placed at the root of your domain name:

title: codecanyon
date: 2019-02-14 11:26:50
cover_detail: /portfolio/assets/coverdetail.jpg
cover_index: /portfolio/assets/cover.jpg
