### ISSUE TITLE
Question about removing text

### ISSUE THREAD

**Issue by flowtrader2016** [klugjo/hexo-theme-magnetic#28]
Hi,

This is a really nice clean template thanks so much for making it!  I am putting together an artist portfolio page containing artwork that is very minimal.  I like the clean look of this template but want a super minimal look and do not want any additional text like the Hexo theme by Jonathan K etc.  Pixel hint have said it is ok to remove the "Template by Pixel Hint" but I wanted to ask you about your text/link.

I do appreciate you put work into this so wanted to ask.  I hope it is ok to ask this question.  

Many thanks again for this.

**Comment by klugjo** [comment]
Sure feel free to remove it. No problem and thanks for the kind words, glad you like it !

**Comment by flowtrader2016** [comment]
Thank you for your reply.  You are very kind!  Have a great weekend.
