### ISSUE TITLE
How to change cover_index

### ISSUE THREAD

**Issue by asnahu** [klugjo/hexo-theme-magnetic#3]
I've been try many times, for example:

```
cover_index: "img/img01.jpg"
cover_index: "img/img02.jpg"
```

```
cover_index: "img/img01.jpg" "img/img02.jpg"
```

```
cover_index: "img/img01.jpg", "img/img02.jpg"
```

```
cover_index: "img/img01.jpg"; "img/img02.jpg"
```

```
cover_index: "img/img01.jpg" / "img/img02.jpg"
```

above all it still not works, so please tell me how to do it correctly, thanks!

**Comment by klugjo** [comment]
Hi,

Do you have a live example of the site so I can see the problem or give me debug information ?

Thanks

**Comment by klugjo** [comment]
Closing this as I am not getting any updates
