### ISSUE TITLE
how to specify the pictures of index and pages?

### ISSUE THREAD

**Issue by wangjiangchuan** [klugjo/hexo-theme-magnetic#5]
I dont know how to custom the pictures of index and pages, I use like this: 
cover_detail: /assets/milkway.jpg
I just put the assets floder in the floder  /_posts/ . But it doesn`t work. Could you told me how to solve the problem?

**Comment by klugjo** [comment]
If you want to use `cover_detail: /assets/milkway.jpg`, you need to put the `assets` folder inside the `source` folder.

If ever in doubt, check the `public` folder that is generated after you execute `hexo generate`, it will show you the structure of your generated blog.

Let me know if that solves your issue.

Thanks

**Comment by L-value** [comment]
hi  klugjo, I have a question that how should I post the article with a different index page cover image everytime.Now I post articles  everytime  these use the default index page cover image.

**Comment by L-value** [comment]
hi  klugjo, I have a question that how should I post the article with a different index page cover image .Now I post articles  everytime  these use the default index page cover image.

**Comment by klugjo** [comment]
In the front matter (the YAML header of each post), you can specify an image

for example

cover_index: /assets/work1.jpg

put the work1.jpg image in /source/assets/work1.jpg

**Comment by L-value** [comment]
Just now I tried and got the results I want.  thank you~

**Comment by wangjiangchuan** [comment]
Thank you a lot.

At 2016-08-13 11:42:16, "Klughertz Jonathan" notifications@github.com wrote:

In the front matter (the YAML header of each post), you can specify an image

for example

cover_index: /assets/work1.jpg

put the work1.jpg image in /source/assets/work1.jpg
