### ISSUE TITLE
Help,Where can I set the HomeImage and Detail Image for each post?

### ISSUE THREAD

**Issue by Homosum** [klugjo/hexo-theme-magnetic#7]
Over read the README.md, I am still confused about  the setting  of the post's image,which file should I write into to set a image for my posts? "cover_index:...","cover_detail:...",where to put these sentences?

**Comment by klugjo** [comment]
Hi, you should put this in the front matter for each post.

Example if you have a post called Welcome to my blog in

`src/posts/welcome-to-my-blog.md`, in the header you will have something like

```
title: Welcome To My Blog
date: 2013/7/13 20:46:25
---
```

Here just add the cover_index and cover_detail to specify a thumbnail and cover image for **that specific post**

example:

```
title: Welcome To My Blog
date: 2013/7/13 20:46:25
cover_detail: /img/welcome1.jpg
cover_index: /img/welcome2.jpg
---
```

Does that make sense ?

**Comment by Homosum** [comment]
solved,thanks!
