### ISSUE TITLE
Archive page sort display

### ISSUE THREAD

**Issue by 1a57danc3** [klugjo/hexo-theme-magnetic#8]
http://www.codeblocq.com/assets/projects/hexo-theme-magnetic/archives/

archive page can sort by date？

look like this.

http://blog.zhangruipeng.me/hexo-theme-minos/archives/

**Comment by klugjo** [comment]
It is already sorted by date.

Both links are the same.

Do you want to display the date ?

**Comment by 1a57danc3** [comment]
> It is already sorted by date.
> 
> Both links are the same.
> 
> Do you want to display the date ?
> 

thx
